[build]
  # Build command (not needed for static site)
  command = "echo 'No build step required'"
  
  # Directory to publish (current directory)
  publish = "."

[build.environment]
  # Node.js version (if needed for any future enhancements)
  NODE_VERSION = "18"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Cache static assets for 1 year
    Cache-Control = "public, max-age=31536000, immutable"

# Specific cache settings for HTML
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Cache settings for CSS and JS
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Enable gzip compression
[[headers]]
  for = "/*"
  [headers.values]
    # Enable compression
    Content-Encoding = "gzip"

# Redirect rules (if needed)
[[redirects]]
  from = "/search"
  to = "/"
  status = 301

[[redirects]]
  from = "/home"
  to = "/"
  status = 301

# 404 page redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Form handling (if you add contact forms later)
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Environment variables (for API keys - use Netlify dashboard to set these securely)
# Don't put actual API keys here - use Netlify's environment variables section
